export function dossierToFe02Draft(dossier,ids){
  if(!dossier?.source) throw new Error("resolved source required for FE-02 draft");
  if(!ids?.source_id||!ids?.provenance_id) throw new Error("source_id and provenance_id required");

  const claimIds=ids.claim_ids||[];
  const evidenceIds=ids.evidence_ids||[];

  if(claimIds.length!==dossier.claims.length) throw new Error("claim_ids length mismatch");

  const evidenceCount=dossier.claims.reduce((n,c)=>n+(c.evidence||[]).length,0);
  if(evidenceIds.length!==evidenceCount) throw new Error("evidence_ids length mismatch");

  const source={
    id:ids.source_id,
    kind:dossier.source.kind,
    tier:dossier.source.tier,
    title:dossier.source.title,
    canonical_url:dossier.source.url,
    external_ids:{primary:dossier.source.external_id},
    author_ids:[],
    organization_ids:[],
    published_at:null,
    status:dossier.publication_status==="unresolved"?"unknown":dossier.publication_status,
    version:1,
    supersedes_source_id:null,
    review_state:"machine_proposed",
    observed_at:dossier.observed_at,
    valid_from:dossier.observed_at,
    valid_to:null
  };

  const provenance={
    id:ids.provenance_id,
    source_id:ids.source_id,
    retrieved_at:dossier.observed_at,
    canonical_url:dossier.source.url,
    external_version:null,
    content_hash:null,
    license:null,
    independence_group:dossier.independence[0]?.group||"source:"+dossier.source.external_id,
    derived_from_source_ids:[],
    notes:"Generated by FE-03; human review pending.",
    observed_at:dossier.observed_at,
    valid_from:dossier.observed_at,
    valid_to:null
  };

  let evidenceIndex=0;
  const bundles=dossier.claims.map((claim,index)=>{
    const localEvidence=[];
    for(const item of claim.evidence||[]){
      localEvidence.push({
        id:evidenceIds[evidenceIndex++],
        claim_id:claimIds[index],
        source_id:ids.source_id,
        provenance_id:ids.provenance_id,
        support:item.support,
        locator:item.locator,
        excerpt_hash:item.excerpt_hash??null,
        notes:null,
        observed_at:dossier.observed_at,
        valid_from:dossier.observed_at,
        valid_to:null
      });
    }

    return {
      claim:{
        id:claimIds[index],
        text:claim.text,
        claim_type:claim.claim_kind==="negative_result"?"negative_result":claim.claim_kind==="limitation"?"limitation":"result",
        evidence_ids:localEvidence.map(x=>x.id),
        confidence:dossier.safety.confidence_ceiling,
        review_state:"machine_proposed",
        observed_at:dossier.observed_at,
        valid_from:dossier.observed_at,
        valid_to:null,
        supersedes_claim_id:null
      },
      evidence:localEvidence
    };
  });

  return {
    source,
    provenance,
    claims:bundles.map(x=>x.claim),
    evidence:bundles.flatMap(x=>x.evidence),
    human_review_required:true,
    safety_decision:dossier.safety.decision
  };
}
